on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to test
    steps:
    - name: Hello world action step
      id: hello
      uses: hyeomans/obtencion-datos-covid19@v1
    # Use the output from the `hello` step
